---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-toolkit-staging
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: devops-toolkit
  install: {}
  interval: 30s
  targetNamespace: staging
  values:
    image:
      tag: 2.9.17
    ingress:
      host: staging.devops-toolkit.https://4B353002CB0C5B8AECB30FB04FDB1A35.gr7.us-west-2.eks.amazonaws.com.nip.io

