---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-toolkit-staging
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: devops-toolkit
  install: {}
  interval: 30s
  targetNamespace: staging
  values:
    image:
      tag: 2.9.9
    ingress:
      host: staging.devops-toolkit.a5ea67e78e4a147a3b9f7ecc3f963c45-911b97f84cb91d41.elb.us-west-2.amazonaws.com.nip.io

